#!/bin/sh

# For BruteForceDES
# Data to mesure "Speedup"

for threads in $(seq 1 16)
	do 
		echo "Threads : $threads" >> output/BruteForceDES/speedup.log
		for i in $(seq 1 20)
			do
				echo "Experiment : $i" >> output/BruteForceDES/speedup.log
				java -cp ./build/classes hw2.BruteForceDES $threads 20 > output/BruteForceDES/speedup.log
			done
	done

# Data to measure "Scaleup"

for threads in $(seq 1 16)
	do 
		key_size=$((8+$threads))
		echo "Threads : $threads" >> output/BruteForceDES/scaleup.log
		echo "Key size : $key_size" >> output/BruteForceDES/scaleup.log
		for i in $(seq 1 20)
			do
				echo "Experiment : $i" >> output/BruteForceDES/scaleup.log
				java -cp ./build/classes hw2.BruteForceDES $threads $key_size >> output/BruteForceDES/scaleup.log
			done
	done
