#!/bin/sh

# For CoinToss
# Data to mesure "Speedup"

for threads in $(seq 1 16)
	do 
		echo "Threads : $threads" >> output/CoinToss/speedup.log
		for i in $(seq 1 3)
			do
				echo "Experiment : $i" >> output/CoinToss/speedup.log
				java -cp ./build/classes -Xmx4g hw2.CoinFlipMain $threads 1000000000 >> output/CoinToss/speedup.log
			done
	done

# Data to measure "Scaleup"

for threads in $(seq 1 16)
	do 
		iterations=$((1000000000*$threads))
		echo "Threads : $threads" >> output/CoinToss/scaleup.log
		echo "Iterations : $iterations" >> output/CoinToss/scaleup.log
		for i in $(seq 1 3)
			do
				echo "Experiment : $i" >> output/CoinToss/scaleup.log
				java -cp ./build/classes -Xmx4g hw2.CoinFlipMain $threads $iterations >> output/CoinToss/scaleup.log
			done
	done
