#!/bin/sh

# For CoinToss
# Data to mesure "Speedup"

for threads in $(seq 1 16)
	do 
		echo "Threads : $threads" >> output/CoinToss/speedup3.log
		for i in $(seq 1 20)
			do
				echo "Experiment : $i" >> output/CoinToss/speedup3.log
				java -cp ./build/classes -Xmx6g hw2.CoinFlip $threads 1000000000 >> output/CoinToss/speedup3.log
			done
	done

# Data to measure "Scaleup"

for threads in $(seq 1 16)
	do 
		iterations=$((1000000000*$threads))
		echo "Threads : $threads" >> output/CoinToss/scaleup3.log
		echo "Iterations : $iterations" >> output/CoinToss/scaleup3.log
		for i in $(seq 1 5)
			do
				echo "Experiment : $i" >> output/CoinToss/scaleup3.log
				java -cp ./build/classes -Xmx6g hw2.CoinFlip $threads $iterations >> output/CoinToss/scaleup3.log
			done
	done
